import { buildDisplayName, hashPassword, normalizeEmail, nowIso, slugify } from "./auth.js";

function createUser({
  id,
  role,
  email,
  password,
  firstName,
  lastName,
  phone = "",
  bio = "",
  focusTrack = "Career Switch",
  education = "",
  goals = "",
  experience = "",
  privateBadges = false,
  avatarUrl = "",
  achievements = [],
  badges = [],
  certificates = [],
  teacherProfile = null,
  isOriginalAdmin = false,
  moderatorPermissions = { manageUsers: false },
}) {
  const createdAt = nowIso();
  const { salt, passwordHash } = hashPassword(password);

  return {
    id,
    role,
    isOriginalAdmin,
    email: normalizeEmail(email),
    salt,
    passwordHash,
    firstName,
    lastName,
    displayName: buildDisplayName(firstName, lastName),
    phone,
    bio,
    focusTrack,
    education,
    goals,
    experience,
    privateBadges,
    avatarUrl,
    achievements,
    badges,
    certificates,
    moderatorPermissions,
    teacherProfile,
    createdAt,
    updatedAt: createdAt,
  };
}

function createCourse({
  id,
  title,
  teacherId = "",
  teacherName = "edUKai teaching team",
  duration,
  level,
  priceCents,
  summary,
  description,
  brief,
  format,
  imageKey,
  category,
  audience,
  outcomes,
  modules,
  slots,
}) {
  const createdAt = nowIso();

  return {
    id,
    slug: slugify(title),
    title,
    teacherId,
    teacherName,
    duration,
    level,
    priceCents,
    currency: "EGP",
    summary,
    description,
    brief,
    format,
    imageKey,
    category,
    audience,
    outcomes,
    modules,
    slots,
    published: true,
    pendingEdits: [],
    createdBy: "user_admin",
    createdAt,
    updatedAt: createdAt,
  };
}

export function buildSeedData() {
  const users = [
    createUser({
      id: "user_admin",
      role: "admin",
      email: "omarg.dev1@edukai.com",
      password: "MrH@130199",
      firstName: "Omar",
      lastName: "G.",
      bio: "Founder and platform admin keeping the academy growing smoothly.",
      isOriginalAdmin: true,
      moderatorPermissions: { manageUsers: true },
    }),
    createUser({
      id: "user_moderator",
      role: "moderator",
      email: "moderator.1@edukai.com",
      password: "Yumi@1301",
      firstName: "Mariam",
      lastName: "Ramadan",
      bio: "Quality and student-experience moderator.",
      moderatorPermissions: { manageUsers: true },
    }),
    createUser({
      id: "user_teacher_frontend",
      role: "teacher",
      email: "aya.frontend@edukai.com",
      password: "Teach@123",
      firstName: "Aya",
      lastName: "Nabil",
      bio: "Frontend mentor known for practical reviews, calm pacing, and portfolio-focused coaching.",
      focusTrack: "Career Switch",
      teacherProfile: {
        title: "Frontend Engineering Mentor",
        specialty: "React workflows, UI systems, and project critique",
        score: 97,
        students: 24,
        classes: 18,
        growth: "92%",
      },
    }),
    createUser({
      id: "user_student_lina",
      role: "student",
      email: "lina.ahmed@edukai.com",
      password: "Learn@123",
      firstName: "Lina",
      lastName: "Ahmed",
      phone: "01000000001",
      bio: "Frontend learner building cleaner interfaces and stronger project confidence.",
      focusTrack: "Career Switch",
      achievements: ["Completed onboarding checklist", "Shared first frontend demo review"],
      badges: [
        {
          id: "badge_momentum",
          name: "Momentum",
          description: "Attended four live classes in a row and stayed active in the cohort rhythm.",
          public: true,
          earnedAt: "2026-04-14T18:00:00.000Z",
        },
        {
          id: "badge_builder",
          name: "Builder",
          description: "Submitted a polished interface challenge with clear improvement notes.",
          public: true,
          earnedAt: "2026-04-21T19:20:00.000Z",
        },
      ],
      certificates: [
        {
          id: "certificate_frontend_foundations",
          title: "Frontend Foundations Sprint",
          description: "Completed the practical foundations sprint with consistent attendance and project delivery.",
          earnedAt: "2026-04-23T17:30:00.000Z",
        },
      ],
    }),
    createUser({
      id: "user_student_nour",
      role: "student",
      email: "nour.magdy@edukai.com",
      password: "Learn@123",
      firstName: "Nour",
      lastName: "Magdy",
      phone: "01000000002",
      bio: "Learner focused on polishing layout decisions and speaking up during project reviews.",
      focusTrack: "Career Switch",
      achievements: ["Completed weekly replay notes"],
    }),
  ];

  const courses = [
    createCourse({
      id: "course_frontend",
      title: "Frontend Development",
      teacherId: "user_teacher_frontend",
      teacherName: "Aya Nabil",
      duration: "8 Weeks",
      level: "Beginner - Intermediate",
      priceCents: 300000,
      summary: "Build responsive interfaces and real frontend projects with live mentorship.",
      description:
        "This course helps students move from HTML, CSS, and JavaScript fundamentals into real React workflows, API integration, and portfolio-ready projects.",
      brief:
        "A founder-reviewed track focused on clean interface thinking, practical React work, and polished portfolio output.",
      format: "Live classes + replay library",
      imageKey: "frontend",
      category: "technology",
      audience: ["Career switchers", "Junior developers", "Students building portfolios"],
      outcomes: ["Responsive interfaces", "State management", "Portfolio reviews", "Mock interviews"],
      modules: ["UI foundations", "React systems", "API workflows", "Capstone launch"],
      slots: [
        {
          id: "slot_frontend_evening",
          name: "Frontend Evening Cohort",
          days: ["Sunday", "Tuesday", "Thursday"],
          startTime: "18:30",
          durationMinutes: 120,
          capacity: 20,
          location: "Online Classroom A",
          recordings: [],
          chatMessages: [],
        },
        {
          id: "slot_frontend_weekend",
          name: "Frontend Weekend Cohort",
          days: ["Friday", "Saturday"],
          startTime: "13:00",
          durationMinutes: 150,
          capacity: 16,
          location: "Online Classroom B",
          recordings: [],
          chatMessages: [],
        },
      ],
    }),
    createCourse({
      id: "course_english",
      title: "English Language",
      duration: "6 Weeks",
      level: "All Levels",
      priceCents: 120000,
      summary: "Build fluency and speaking confidence with guided live practice.",
      description:
        "Students practice conversation, listening, writing, and presentation clarity in a warm, structured learning space.",
      brief:
        "A confidence-first language track built around conversation, consistency, and real speaking practice.",
      format: "Speaking labs + practice circles",
      imageKey: "english",
      category: "language",
      audience: ["School learners", "University students", "Professionals improving fluency"],
      outcomes: ["Speaking confidence", "Listening stamina", "Writing feedback", "Presentation practice"],
      modules: ["Diagnostic placement", "Conversation labs", "Presentation coaching", "Certification prep"],
      slots: [
        {
          id: "slot_english_morning",
          name: "English Morning Circle",
          days: ["Monday", "Wednesday"],
          startTime: "10:00",
          durationMinutes: 90,
          capacity: 18,
          location: "Online Classroom C",
          recordings: [],
          chatMessages: [],
        },
      ],
    }),
    createCourse({
      id: "course_interpretation",
      title: "Simultaneous Interpretation",
      duration: "6 Weeks",
      level: "Advanced",
      priceCents: 500000,
      summary: "Train under pressure with conference-style interpretation drills.",
      description:
        "Students work on listening control, memory, terminology, and calm live delivery inside realistic interpretation scenarios.",
      brief:
        "A high-focus track designed around intense live practice and structured review.",
      format: "Workshop-based",
      imageKey: "interpretation",
      category: "language",
      audience: ["Language specialists", "Advanced English learners", "Aspiring interpreters"],
      outcomes: ["Conference drills", "Memory techniques", "Pressure handling", "Feedback recordings"],
      modules: ["Listening control", "Interpretation drills", "Live event simulation", "Mentor review"],
      slots: [
        {
          id: "slot_interpretation_evening",
          name: "Interpretation Intensive",
          days: ["Saturday"],
          startTime: "17:00",
          durationMinutes: 180,
          capacity: 12,
          location: "Online Classroom D",
          recordings: [],
          chatMessages: [],
        },
      ],
    }),
    createCourse({
      id: "course_hr",
      title: "Human Resources Management",
      duration: "12 Weeks",
      level: "Beginner",
      priceCents: 280000,
      summary: "Understand hiring, onboarding, and people operations through practical scenarios.",
      description:
        "Students learn the real operating side of HR, from recruitment and interviews to workforce planning and policy basics.",
      brief:
        "A practical people-operations course for learners who want less theory and more operating clarity.",
      format: "Case-study sessions",
      imageKey: "hr",
      category: "business",
      audience: ["New HR staff", "Operations leads", "People team assistants"],
      outcomes: ["Recruitment workflows", "People operations", "Policy writing", "Interview design"],
      modules: ["Hiring systems", "Performance reviews", "Workforce analytics", "Policy clinic"],
      slots: [
        {
          id: "slot_hr_evening",
          name: "HR Foundations Cohort",
          days: ["Monday", "Thursday"],
          startTime: "19:00",
          durationMinutes: 120,
          capacity: 24,
          location: "Online Classroom E",
          recordings: [],
          chatMessages: [],
        },
      ],
    }),
  ];

  return {
    users,
    courses,
    jobs: [
      {
        id: "job_frontend",
        title: "Frontend Developer",
        department: "Development",
        location: "Remote / Cairo Office",
        type: "Full-Time",
        description: "Work on modern web interfaces using React and Tailwind CSS to deliver world-class learning experiences.",
      },
      {
        id: "job_english",
        title: "English Language Instructor",
        department: "Education",
        location: "Remote / Alexandria Office",
        type: "Part-Time",
        description: "Guide learners through English grammar, fluency, and communication skills in engaging sessions.",
      },
      {
        id: "job_hr",
        title: "HR Instructor",
        department: "Education",
        location: "Remote / Hybrid",
        type: "Part-Time",
        description: "Teach Human Resources concepts and real-world applications to students in our mentorship-based courses.",
      },
    ],
    enrollments: [
      {
        id: "enrollment_lina_frontend",
        userId: "user_student_lina",
        courseId: "course_frontend",
        slotId: "slot_frontend_evening",
        selectedDays: ["Sunday", "Tuesday", "Thursday"],
        daysPerWeek: 3,
        status: "active",
        paymentStatus: "deposit_paid",
        enrolledAt: "2026-04-08T18:30:00.000Z",
      },
      {
        id: "enrollment_nour_frontend",
        userId: "user_student_nour",
        courseId: "course_frontend",
        slotId: "slot_frontend_evening",
        selectedDays: ["Sunday", "Tuesday", "Thursday"],
        daysPerWeek: 3,
        status: "active",
        paymentStatus: "deposit_paid",
        enrolledAt: "2026-04-09T18:30:00.000Z",
      },
    ],
    feedback: [
      {
        id: "feedback_lina_frontend_1",
        studentId: "user_student_lina",
        teacherId: "user_teacher_frontend",
        courseId: "course_frontend",
        score: 92,
        comment:
          "Your component structure is much cleaner now. Keep naming props clearly and explain one interface choice during each review.",
        createdAt: "2026-04-20T17:00:00.000Z",
      },
      {
        id: "feedback_lina_frontend_2",
        studentId: "user_student_lina",
        teacherId: "user_teacher_frontend",
        courseId: "course_frontend",
        score: 95,
        comment:
          "The latest landing page felt calmer and easier to scan. Keep the same spacing discipline when you build the next dashboard screen.",
        createdAt: "2026-04-24T17:45:00.000Z",
      },
      {
        id: "feedback_nour_frontend_1",
        studentId: "user_student_nour",
        teacherId: "user_teacher_frontend",
        courseId: "course_frontend",
        score: 88,
        comment:
          "Strong progress on layout consistency. Focus next on trimming repeated text blocks so the interface breathes more easily.",
        createdAt: "2026-04-22T16:30:00.000Z",
      },
    ],
    payments: [],
    sessions: [],
    reminders: [],
    notifications: [
      {
        id: "notification_lina_feedback",
        userId: "user_student_lina",
        type: "feedback",
        title: "New teacher feedback",
        message: "Aya Nabil left a fresh note on your Frontend Development progress.",
        link: "/",
        read: false,
        createdAt: "2026-04-24T17:45:00.000Z",
        meta: {},
      },
      {
        id: "notification_lina_badge",
        userId: "user_student_lina",
        type: "badge",
        title: "Badge earned",
        message: "You earned the Builder badge for your latest interface challenge.",
        link: "/",
        read: false,
        createdAt: "2026-04-21T19:20:00.000Z",
        meta: {},
      },
    ],
    conversations: [],
    meetings: [],
    communityPosts: [],
    profileComments: [
      {
        id: "profile_comment_lina_1",
        authorId: "user_student_nour",
        targetUserId: "user_student_lina",
        body: "Your UI notes always make the project steps easier to follow for the rest of us.",
        createdAt: "2026-04-19T12:15:00.000Z",
      },
    ],
    peerFeedback: [
      {
        id: "peer_feedback_lina_1",
        authorId: "user_student_nour",
        targetUserId: "user_student_lina",
        courseId: "course_frontend",
        body: "You explain layout fixes in a really clear way. The before-and-after comparisons help the whole class.",
        score: 5,
        tone: "supportive",
        createdAt: "2026-04-21T14:30:00.000Z",
      },
    ],
    courseRatings: [
      {
        id: "rating_english_lina",
        courseId: "course_english",
        userId: "user_student_lina",
        rating: 5,
        review: "Clear speaking practice with useful feedback loops.",
        createdAt: "2026-04-18T10:00:00.000Z",
        updatedAt: "2026-04-18T10:00:00.000Z",
      },
      {
        id: "rating_hr_nour",
        courseId: "course_hr",
        userId: "user_student_nour",
        rating: 4,
        review: "Practical examples and a very structured class rhythm.",
        createdAt: "2026-04-17T10:00:00.000Z",
        updatedAt: "2026-04-17T10:00:00.000Z",
      },
    ],
    assignmentSubmissions: [],
  };
}
